apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cake-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/orderdb"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: ORDER_COMPLETED_QUEUE
              value: "order.completed"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:3001"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
